### ISSUE TITLE
Clean UP & Dockerization eos8lok

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8lok#8]

**Comment by febielin** [comment]
This model currently does not pass the upload to dockerhub action.
```
#9 119.0 🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨
#9 119.0 
#9 119.0 Error message:
#9 119.0 
#9 119.0 'CondaEnvironmentService' object has no attribute 'pid'
```

**Comment by febielin** [comment]
Hi @GemmaTuron,

I'm having a hard time testing this model. 

Because the upload to dockerhub workflow failed, I am unable to fetch the image from docker. [Colab](https://colab.research.google.com/drive/19udfP0raLxmE1DBzUg7jxfIOW8iPvCVP?usp=sharing) gives me the Nonetype error. I also experience issues on CLI: [eos8lok_error.log](https://github.com/ersilia-os/eos8lok/files/12021445/eos8lok_error.log).

In regards to reformatting, at first glance, this model seems to follow the eos template. My main concern is just getting this model to work.  

@emmakodes suggested that you or Miquel may have already looked into this [dockerhub pid error](https://github.com/ersilia-os/eos8lok/actions/runs/5392143366/jobs/9790065922#step:7:16674). Can we rerun the upload to dockerhub workflow to see if it works?

[UPDATE] It works on codespaces. ([eos8lok_codespaces.log](https://github.com/ersilia-os/eos8lok/files/12021994/eos8lok_codespaces.log), [eos8lok_output.csv](https://github.com/ersilia-os/eos8lok/files/12021988/eos8lok_output.csv)) Though I would still like to rerun the workflow to be sure.

**Comment by GemmaTuron** [comment]
Hi @febielin 
Please, go through the error logs and point us to what might be the cause of the error. I see:
`/var/folders/mx/mxb7172x3czgb85qcdk0k1dw0000gn/T/ersilia-mxdcqcuf/script.sh: line 9: 26643 Segmentation fault: 11  python pack.py` So it seems is a MAC related issue and not a model issue.
Also, the first thing to do is not fetch the model but clone it and fetch from local, otherwise it is not possible to work on it.

**Comment by GemmaTuron** [comment]
The tests have now passed completely
I don't know about the pid error... but you can see if any refactoring is needed and open a PR. If not, we'll move on and consider this model done, it is quite new anyway!

**Comment by febielin** [comment]
Colab works now. Output is [here](https://drive.google.com/file/d/1_FVAGXrX1lB1EHGU4mRItmYj0H63ieF5/view?usp=sharing)

Also, in regards to working on the model locally, I fork, clone, and make changes to the model, but I am unable to fetch it locally through --repo_path. I get the segmentation fault Mac error.

**Comment by GemmaTuron** [comment]
@febielin 
Then open a PR, let's not worry about the segmentation fault error for the moment

**Comment by febielin** [comment]
Hi @GemmaTuron,

As mentioned [here](https://github.com/ersilia-os/ersilia/issues/711#issuecomment-1632600523), this model seems to follow the eos template already. I've done some testing as well, and the model is working well. I don't believe a PR will be necessary this time. Can we consider this done?

**Comment by GemmaTuron** [comment]
yes, this was incorporated by Emmanuel a few weeks ago. If you have tested and the model is working we can close this!
